# Generated by Django 4.2.2 on 2023-06-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_name_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
